services:

  qbittorrent:
    image: linuxserver/qbittorrent:4.6.5
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - WEBUI_PORT=8080
      - WEBUI_USERNAME=admin
      - WEBUI_PASSWORD=111111
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./qbit-config:/config
      - /data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - media-net


  media-bot:
    build: ./media-bot
    container_name: media-bot
    command: ["python", "-u", "runner.py"]
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - QBIT_URL=http://qbittorrent:8080
      - QBIT_USER=admin
      - QBIT_PASS=111111
    volumes:
      - ./media-bot/data:/app/data
      - /data/movies:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - media-net


  media-bot-post:
    build: ./media-bot
    container_name: media-bot-post
    command: ["python", "-u", "post_processor.py"]
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - QBIT_URL=http://qbittorrent:8080
      - QBIT_USER=admin
      - QBIT_PASS=111111
    volumes:
      - ./media-bot/data:/app/data
      - /data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - media-net


  movie-agent:
    image: python:3.11-slim
    container_name: movie-agent
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
      pip install --no-cache-dir flask requests &&
      python agent.py
      "
    ports:
      - "5001:5001"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./movie-agent:/app
      - ./media-bot/data:/app/data
      - /data/movies:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - media-net


  javinizer:
    image: javinizer/javinizer:latest-cli
    container_name: javinizer
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /data/movies:/data
      - /docker/media-stack/javinizer-config:/root/.local/share/javinizer
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - media-net
    command:
      - pwsh
      - -Command
      - >
        Import-Module Javinizer;
        while ($$true) {
          Javinizer -Path '/data' -DestinationPath '/data' -Recurse;
          Start-Sleep -Seconds 300
        }


  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./jellyfin-config:/config
      - /data:/media
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - media-net


  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - media-net


networks:
  media-net:
    driver: bridge